title: Cameron Fraser's Internet Place
description: >-
  This web site is under construction. It will eventually contain some good
  content put there by Cameron Fraser, a computer guy and urbanist nerd from
  Seattle.
url: "https://fraser.cam"

plugins:
  - jekyll-feed

collections:
  posts:
    permalink: /words/:slug

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
